/* AlgebraTrace UI: LaTeX-first math rendering and conversion.
 * The visible editor stores LaTeX. The solver receives a normalized plain-text
 * expression generated by latexToPlain(). No CDN, no server, no external fonts.
 */
window.AlgebraTrace = window.AlgebraTrace || {};
(function (NS) {
    "use strict";

    function safeText(v) { return String(v === undefined || v === null ? "" : v); }
    function escapeHTML(text) {
        return safeText(text)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;");
    }
    function trim(text) { return safeText(text).trim(); }
    function normalizeSymbols(text) {
        return safeText(text)
            .replace(/−/g, "-")
            .replace(/≤/g, "<=")
            .replace(/≥/g, ">=")
            .replace(/≠/g, "!=")
            .replace(/π/g, "\\pi")
            .replace(/∞/g, "\\infty");
    }
    function skipSpaces(s, i) { while (i < s.length && /\s/.test(s.charAt(i))) i += 1; return i; }
    function isLetter(ch) { return /[A-Za-z]/.test(ch || ""); }
    function readCommand(s, slash) {
        var i = slash + 1;
        if (i >= s.length) return { name:"", end:i };
        if (!isLetter(s.charAt(i))) return { name:s.charAt(i), end:i + 1 };
        var start = i;
        while (i < s.length && isLetter(s.charAt(i))) i += 1;
        return { name:s.slice(start, i), end:i };
    }
    function matchingClose(open) { return open === "{" ? "}" : (open === "(" ? ")" : (open === "[" ? "]" : "")); }
    function readDelimited(s, pos) {
        pos = skipSpaces(s, pos);
        var open = s.charAt(pos), close = matchingClose(open);
        if (!close) return null;
        var depth = 0;
        for (var i = pos; i < s.length; i += 1) {
            var ch = s.charAt(i);
            if (ch === "\\") { i += readCommand(s, i).end - i - 1; continue; }
            if (ch === open) depth += 1;
            else if (ch === close) {
                depth -= 1;
                if (depth === 0) return { outerStart:pos, contentStart:pos + 1, contentEnd:i, outerEnd:i + 1, open:open, close:close };
            }
        }
        return null;
    }
    function readScriptGroup(s, pos) {
        pos = skipSpaces(s, pos);
        var g = readDelimited(s, pos);
        if (g && g.open === "{") return g;
        if (pos < s.length) return { outerStart:pos, contentStart:pos, contentEnd:pos + 1, outerEnd:pos + 1, open:"", close:"" };
        return null;
    }
    function readFunctionArgument(s, pos) {
        pos = skipSpaces(s, pos);
        var g = readDelimited(s, pos);
        if (g && (g.open === "{" || g.open === "(" || g.open === "[")) return g;
        return null;
    }
    function rangeAttrs(start, end) {
        return ' data-start="' + start + '" data-end="' + end + '"';
    }
    function commandHTML(name) {
        var map = {
            pi:"π", infty:"∞", infinity:"∞", cdot:"·", times:"×", div:"÷",
            le:"≤", leq:"≤", ge:"≥", geq:"≥", neq:"≠", ne:"≠",
            to:"→", rightarrow:"→", pm:"±"
        };
        return map[name] || name;
    }

    function renderLatexContent(src, options) {
        src = safeText(src);
        options = options || {};
        var caret = typeof options.caret === "number" ? options.caret : null;
        var caretRendered = false;
        function caretHTML() { caretRendered = true; return '<span class="editor-caret" aria-hidden="true"></span>'; }
        function boundary(pos) { return (caret !== null && !caretRendered && caret === pos) ? caretHTML() : ""; }
        function charSpan(i, shown, cls) {
            return boundary(i) + '<span class="' + (cls || "mchar") + '" data-pos="' + i + '" data-start="' + i + '" data-end="' + (i + 1) + '">' + escapeHTML(shown) + '</span>';
        }
        function renderOperator(i, raw, shown, len) {
            len = len || raw.length || 1;
            return boundary(i) + '<span class="op"' + rangeAttrs(i, i + len) + '>' + escapeHTML(shown) + '</span>' + boundary(i + len);
        }
        function renderDelimiters(open, close, group) {
            return '<span class="paren"' + rangeAttrs(group.outerStart, group.contentStart) + '>' + escapeHTML(open) + '</span>' +
                renderRange(group.contentStart, group.contentEnd) +
                '<span class="paren"' + rangeAttrs(group.contentEnd, group.outerEnd) + '>' + escapeHTML(close) + '</span>';
        }
        function renderGroupOnly(group) { return renderRange(group.contentStart, group.contentEnd); }
        function renderCommand(i, cmd) {
            var name = cmd.name;
            var lower = name.toLowerCase();
            var end = cmd.end;
            if (lower === "left" || lower === "right") return { html:boundary(i), end:end };
            if (lower === "frac") {
                var num = readDelimited(src, end), den = num ? readDelimited(src, num.outerEnd) : null;
                if (num && den) {
                    var numeratorText = src.slice(num.contentStart, num.contentEnd).replace(/\s+/g, "");
                    var denominatorText = src.slice(den.contentStart, den.contentEnd).replace(/\s+/g, "");
                    if (/^d$/.test(numeratorText) && /^d[a-zA-Z]$/.test(denominatorText)) {
                        return { html:'<span class="frac derivative-frac"' + rangeAttrs(i, den.outerEnd) + '><span class="num">d</span><span class="den">d' + escapeHTML(denominatorText.slice(1)) + '</span></span>', end:den.outerEnd };
                    }
                    return { html:'<span class="frac"' + rangeAttrs(i, den.outerEnd) + '><span class="num">' + renderGroupOnly(num) + '</span><span class="den">' + renderGroupOnly(den) + '</span></span>', end:den.outerEnd };
                }
            }
            if (lower === "sqrt") {
                var rad = readDelimited(src, end);
                if (rad) return { html:'<span class="sqrt"' + rangeAttrs(i, rad.outerEnd) + '><span class="radical">√</span><span class="radicand">' + renderGroupOnly(rad) + '</span></span>', end:rad.outerEnd };
            }
            if (/^(sin|cos|tan|ctg|cot|sec|csc|ln|exp)$/.test(lower)) {
                var arg = readFunctionArgument(src, end);
                var fn = '<span class="fn"' + rangeAttrs(i, end) + '>' + escapeHTML(lower) + '</span>';
                if (arg) return { html:fn + renderDelimiters(arg.open === "{" ? "(" : arg.open, arg.open === "{" ? ")" : arg.close, arg), end:arg.outerEnd };
                return { html:fn, end:end };
            }
            if (lower === "log") {
                var pos = skipSpaces(src, end), base = null;
                if (src.charAt(pos) === "_") {
                    var baseGroup = readScriptGroup(src, pos + 1);
                    if (baseGroup) { base = baseGroup; pos = baseGroup.outerEnd; }
                }
                var argLog = readFunctionArgument(src, pos);
                var logHTML = '<span class="fn"' + rangeAttrs(i, base ? base.outerEnd : end) + '>log' + (base ? '<sub class="log-base">' + renderGroupOnly(base) + '</sub>' : '') + '</span>';
                if (argLog) {
                    var argPlainText = src.slice(argLog.contentStart, argLog.contentEnd).replace(/\s+/g, "");
                    return { html:logHTML + '<span class="fn-arg" data-arg-text="' + escapeHTML(argPlainText) + '">' + renderDelimiters(argLog.open === "{" ? "(" : argLog.open, argLog.open === "{" ? ")" : argLog.close, argLog) + '</span>', end:argLog.outerEnd };
                }
                return { html:logHTML, end:base ? base.outerEnd : end };
            }
            var known = commandHTML(lower);
            if (known !== lower || lower === "pi" || lower === "infty") return { html:boundary(i) + '<span class="mchar"' + rangeAttrs(i, end) + '>' + escapeHTML(known) + '</span>' + boundary(end), end:end };
            return { html:boundary(i) + '<span class="mtext"' + rangeAttrs(i, end) + '>\\' + escapeHTML(name) + '</span>' + boundary(end), end:end };
        }
        function renderRange(start, end) {
            var html = "";
            for (var i = start; i < end;) {
                var ch = src.charAt(i);
                if (caret !== null && caret === i) html += boundary(i);
                if (ch === "\\") {
                    var cmd = readCommand(src, i);
                    var rendered = renderCommand(i, cmd);
                    html += rendered.html;
                    i = rendered.end;
                    continue;
                }
                if (ch === "^") {
                    var exp = readScriptGroup(src, i + 1);
                    if (exp) {
                        html += '<sup class="power-exp"' + rangeAttrs(i, exp.outerEnd) + '>' + renderGroupOnly(exp) + '</sup>';
                        i = exp.outerEnd;
                        continue;
                    }
                }
                if (ch === "_") {
                    var sub = readScriptGroup(src, i + 1);
                    if (sub) {
                        html += '<sub' + rangeAttrs(i, sub.outerEnd) + '>' + renderGroupOnly(sub) + '</sub>';
                        i = sub.outerEnd;
                        continue;
                    }
                }
                if (ch === "{") {
                    var br = readDelimited(src, i);
                    if (br) { html += renderGroupOnly(br); i = br.outerEnd; continue; }
                }
                if (ch === "(" || ch === "[" || ch === ")" || ch === "]") {
                    html += charSpan(i, ch, "paren"); i += 1; continue;
                }
                if (ch === "<" && src.charAt(i + 1) === "=") { html += renderOperator(i, "<=", "≤", 2); i += 2; continue; }
                if (ch === ">" && src.charAt(i + 1) === "=") { html += renderOperator(i, ">=", "≥", 2); i += 2; continue; }
                if (ch === "!" && src.charAt(i + 1) === "=") { html += renderOperator(i, "!=", "≠", 2); i += 2; continue; }
                if ("=<>+-".indexOf(ch) >= 0) { html += renderOperator(i, ch, ch === "-" ? "−" : ch, 1); i += 1; continue; }
                if (ch === "*") { html += renderOperator(i, ch, "·", 1); i += 1; continue; }
                if (ch === "/") { html += renderOperator(i, ch, "/", 1); i += 1; continue; }
                if (ch === ";" || ch === ",") { html += renderOperator(i, ch, ch, 1); i += 1; continue; }
                if (/\s/.test(ch)) { html += '<span class="math-space"' + rangeAttrs(i, i + 1) + '></span>'; i += 1; continue; }
                html += charSpan(i, ch);
                i += 1;
            }
            if (caret !== null && caret === end) html += boundary(end);
            return html;
        }
        var content = renderRange(0, src.length);
        if (caret !== null && !caretRendered) content += caretHTML();
        return content || (options.emptySlot ? '<span class="editor-slot">□</span>' : "");
    }

    function stripOuterParens(s) {
        s = trim(s);
        var changed = true;
        while (changed && s.length >= 2 && s.charAt(0) === "(" && s.charAt(s.length - 1) === ")") {
            changed = false;
            var depth = 0, ok = true;
            for (var i = 0; i < s.length; i += 1) {
                if (s.charAt(i) === "(") depth += 1;
                else if (s.charAt(i) === ")") depth -= 1;
                if (depth === 0 && i < s.length - 1) { ok = false; break; }
            }
            if (ok) { s = trim(s.slice(1, -1)); changed = true; }
        }
        return s;
    }
    function findTopLevelChar(s, chars, fromRight) {
        var depth = 0, abs = false;
        var i = fromRight ? s.length - 1 : 0, end = fromRight ? -1 : s.length, step = fromRight ? -1 : 1;
        for (; i !== end; i += step) {
            var ch = s.charAt(i);
            if (fromRight) { if (ch === ")") depth += 1; else if (ch === "(") depth -= 1; }
            else { if (ch === "(") depth += 1; else if (ch === ")") depth -= 1; }
            if (ch === "|") abs = !abs;
            if (depth === 0 && !abs && chars.indexOf(ch) >= 0) {
                if ((ch === "+" || ch === "-") && i === 0) continue;
                return i;
            }
        }
        return -1;
    }
    function findTopLevelRelation(s) {
        var depth = 0, abs = false;
        for (var i = 0; i < s.length; i += 1) {
            var ch = s.charAt(i), two = s.slice(i, i + 2);
            if (ch === "(") depth += 1;
            else if (ch === ")") depth -= 1;
            else if (ch === "|") abs = !abs;
            if (depth === 0 && !abs) {
                if (two === "<=" || two === ">=" || two === "!=") return { index:i, op:two, length:2 };
                if (ch === "=" || ch === "<" || ch === ">") return { index:i, op:ch, length:1 };
            }
        }
        return null;
    }
    function splitTopLevelList(s, delimiter) {
        var out = [], start = 0, depth = 0, abs = false;
        for (var i = 0; i < s.length; i += 1) {
            var ch = s.charAt(i);
            if (ch === "(") depth += 1;
            else if (ch === ")") depth -= 1;
            else if (ch === "|") abs = !abs;
            if (depth === 0 && !abs && ch === delimiter) { out.push(s.slice(start, i)); start = i + 1; }
        }
        out.push(s.slice(start));
        return out;
    }
    function functionToLatex(name, argText) {
        name = safeText(name);
        var lower = name.toLowerCase();
        var arg = plainToLatexExpression(argText);
        if (lower === "sqrt") return "\\sqrt{" + arg + "}";
        if (lower === "abs") return "\\left|" + arg + "\\right|";
        if (lower === "ln") return "\\ln(" + arg + ")";
        if (lower === "sin" || lower === "cos" || lower === "tan" || lower === "cot") return "\\" + lower + "(" + arg + ")";
        if (lower === "log") {
            var args = splitTopLevelList(argText, ",");
            if (args.length === 2) return "\\log_{" + plainToLatexExpression(args[1]) + "}(" + plainToLatexExpression(args[0]) + ")";
            return "\\log(" + arg + ")";
        }
        if (/^log_/.test(lower)) return "\\log_{" + name.slice(4) + "}(" + arg + ")";
        if (/^log\d+(?:\.\d+)?$/i.test(name)) return "\\log_{" + name.replace(/^log/i, "") + "}(" + arg + ")";
        return "\\operatorname{" + escapeLatex(name) + "}(" + arg + ")";
    }
    function escapeLatex(s) { return safeText(s).replace(/([{}])/g, "\\$1"); }
    function plainToLatexExpression(input) {
        var s = normalizeSymbols(input).replace(/\s+/g, "");
        if (!s) return "";
        s = s.replace(/pi/gi, "\\pi").replace(/infinity/gi, "\\infty");
        var rel = findTopLevelRelation(s);
        if (rel) {
            var op = rel.op === "<=" ? "\\le " : (rel.op === ">=" ? "\\ge " : (rel.op === "!=" ? "\\ne " : rel.op));
            return plainToLatexExpression(s.slice(0, rel.index)) + " " + op + " " + plainToLatexExpression(s.slice(rel.index + rel.length));
        }
        var pieces = splitTopLevelList(s, ";");
        if (pieces.length > 1) return pieces.map(plainToLatexExpression).join(";\\quad ");
        if (/^d\/d[a-z]/i.test(s)) return "\\frac{d}{d" + s.match(/^d\/d([a-z])/i)[1] + "}" + plainToLatexExpression(s.replace(/^d\/d[a-z]/i, ""));
        if (/^integrate/i.test(s)) return "\\int " + plainToLatexExpression(s.replace(/^integrate/i, "")) + "\\,dx";
        var limit = s.match(/^limit\((.*)\)$/i);
        if (limit) {
            var args = splitTopLevelList(limit[1], ",");
            if (args.length >= 3) return "\\lim_{" + trim(args[1]) + "\\to " + plainToLatexExpression(args[2]) + "}" + plainToLatexExpression(args[0]);
        }
        s = stripOuterParens(s);
        if (s.charAt(0) === "|" && s.charAt(s.length - 1) === "|") return "\\left|" + plainToLatexExpression(s.slice(1, -1)) + "\\right|";
        var add = findTopLevelChar(s, "+-", true);
        if (add > 0) return plainToLatexExpression(s.slice(0, add)) + " " + (s.charAt(add) === "-" ? "-" : "+") + " " + plainToLatexExpression(s.slice(add + 1));
        var div = findTopLevelChar(s, "/", false);
        if (div > 0) return "\\frac{" + plainToLatexExpression(s.slice(0, div)) + "}{" + plainToLatexExpression(s.slice(div + 1)) + "}";
        var mul = findTopLevelChar(s, "*", false);
        if (mul > 0) return plainToLatexExpression(s.slice(0, mul)) + "\\cdot " + plainToLatexExpression(s.slice(mul + 1));
        var pow = findTopLevelChar(s, "^", false);
        if (pow > 0) return plainToLatexExpression(s.slice(0, pow)) + "^{" + plainToLatexExpression(stripOuterParens(s.slice(pow + 1))) + "}";
        var fn = s.match(/^([A-Za-z]+(?:_[0-9A-Za-z.\/]+)?|log\d+(?:\.\d+)?)\((.*)\)$/);
        if (fn) return functionToLatex(fn[1], fn[2]);
        return escapeLatex(s).replace(/\*/g, "\\cdot ");
    }

    function plainToLatex(text) { return plainToLatexExpression(text); }

    function parseLatexPlain(src, start, end) {
        src = normalizeSymbols(src);
        start = start || 0;
        end = typeof end === "number" ? end : src.length;
        var out = "";
        for (var i = start; i < end;) {
            var ch = src.charAt(i);
            if (/\s/.test(ch)) { i += 1; continue; }
            if (ch === "\\") {
                var cmd = readCommand(src, i);
                var lower = cmd.name.toLowerCase();
                if (lower === "left" || lower === "right") { i = cmd.end; continue; }
                if (lower === "cdot" || lower === "times") { out += "*"; i = cmd.end; continue; }
                if (lower === "div") { out += "/"; i = cmd.end; continue; }
                if (lower === "le" || lower === "leq") { out += "<="; i = cmd.end; continue; }
                if (lower === "ge" || lower === "geq") { out += ">="; i = cmd.end; continue; }
                if (lower === "neq" || lower === "ne") { out += "!="; i = cmd.end; continue; }
                if (lower === "pi") { out += "pi"; i = cmd.end; continue; }
                if (lower === "infty" || lower === "infinity") { out += "infinity"; i = cmd.end; continue; }
                if (lower === "pm") { out += "+/-"; i = cmd.end; continue; }
                if (lower === "frac") {
                    var num = readDelimited(src, cmd.end), den = num ? readDelimited(src, num.outerEnd) : null;
                    if (num && den) {
                        var nText = parseLatexPlain(src, num.contentStart, num.contentEnd);
                        var dText = parseLatexPlain(src, den.contentStart, den.contentEnd);
                        if (nText === "d" && /^d[a-zA-Z]$/.test(dText)) out += "d/" + dText;
                        else out += "(" + nText + ")/(" + dText + ")";
                        i = den.outerEnd; continue;
                    }
                }
                if (lower === "sqrt") {
                    var rad = readDelimited(src, cmd.end);
                    if (rad) { out += "sqrt(" + parseLatexPlain(src, rad.contentStart, rad.contentEnd) + ")"; i = rad.outerEnd; continue; }
                }
                if (/^(sin|cos|tan|cot|ctg|sec|csc|ln|exp)$/.test(lower)) {
                    var arg = readFunctionArgument(src, cmd.end);
                    if (arg) { out += lower + "(" + parseLatexPlain(src, arg.contentStart, arg.contentEnd) + ")"; i = arg.outerEnd; continue; }
                    out += lower; i = cmd.end; continue;
                }
                if (lower === "log") {
                    var pos = skipSpaces(src, cmd.end), base = null;
                    if (src.charAt(pos) === "_") {
                        var bg = readScriptGroup(src, pos + 1);
                        if (bg) { base = parseLatexPlain(src, bg.contentStart, bg.contentEnd); pos = bg.outerEnd; }
                    }
                    var argLog = readFunctionArgument(src, pos);
                    if (argLog) { out += (base ? "log_" + base : "log") + "(" + parseLatexPlain(src, argLog.contentStart, argLog.contentEnd) + ")"; i = argLog.outerEnd; continue; }
                    out += base ? "log_" + base : "log"; i = pos; continue;
                }
                if (lower === ",") { i = cmd.end; continue; }
                out += cmd.name;
                i = cmd.end; continue;
            }
            if (ch === "{") {
                var br = readDelimited(src, i);
                if (br) { out += "(" + parseLatexPlain(src, br.contentStart, br.contentEnd) + ")"; i = br.outerEnd; continue; }
            }
            if (ch === "^") {
                var exp = readScriptGroup(src, i + 1);
                if (exp) { out += "^(" + parseLatexPlain(src, exp.contentStart, exp.contentEnd) + ")"; i = exp.outerEnd; continue; }
            }
            if (ch === "_") {
                var sub = readScriptGroup(src, i + 1);
                if (sub) { out += "_" + parseLatexPlain(src, sub.contentStart, sub.contentEnd); i = sub.outerEnd; continue; }
            }
            if (ch === "≤") { out += "<="; i += 1; continue; }
            if (ch === "≥") { out += ">="; i += 1; continue; }
            if (ch === "≠") { out += "!="; i += 1; continue; }
            if (ch === "·" || ch === "×") { out += "*"; i += 1; continue; }
            if (ch === "÷") { out += "/"; i += 1; continue; }
            out += ch;
            i += 1;
        }
        return out
            .replace(/\)\(/g, ")*(")
            .replace(/\^\(([0-9]+)\)/g, "^$1")
            .replace(/\s+/g, "")
            ;
    }

    function latexToPlain(latex) {
        return parseLatexPlain(latex || "");
    }

    function renderLatex(latex, options) {
        return '<span class="math-render latex-render">' + renderLatexContent(latex, options || {}) + '</span>';
    }

    function renderMath(text) {
        var latex = plainToLatex(text);
        return renderLatex(latex);
    }
    function renderStepMath(text) { return renderMath(text); }
    function mathToLatex(text) { return plainToLatex(text); }

    NS.escapeHTML = NS.escapeHTML || escapeHTML;
    NS.textToLatex = plainToLatex;
    NS.plainToLatex = plainToLatex;
    NS.latexToPlain = latexToPlain;
    NS.renderLatex = renderLatex;
    NS.renderLatexContent = renderLatexContent;
    NS.mathToLatex = mathToLatex;
    NS.renderMath = renderMath;
    NS.renderStepMath = renderStepMath;
})(window.AlgebraTrace);
